"""
Train the local subscription-line classifier.

THE BIG PICTURE
  text line ──> vectorizer (text → numbers) ──> logistic regression ──> P(subscription)

  1. VECTORIZATION — ML models can't read text; they need numbers.
     We use TF-IDF over CHARACTER n-grams (2-5 chars). That means the line
     "NETFLIX.COM" becomes counts of fragments like "netf", "etfl", "flix".
     Character fragments (instead of whole words) are perfect for bank lines
     because banks mangle names: "NETFLIX.COM", "NETFLIX INTL B.V." and
     "netflix.com amsterdam" all share the fragment "netfl".
     TF-IDF then down-weights fragments that appear everywhere (like "06/")
     and up-weights distinctive ones (like "spoti").

  2. MODEL — Logistic Regression: a simple linear model that learns one
     weight per fragment ("seeing 'spoti' pushes toward subscription,
     seeing 'withdr' pushes away"). It's fast, hard to overfit with proper
     regularization, and — critically for us — its predict_proba() output
     is a well-behaved CONFIDENCE score we can threshold against.

  3. CONFIDENCE ROUTING — at runtime we don't just want a yes/no; we want
     "how sure?". If P(sub) is near 0 or 1, trust the local model (free).
     If it's in the uncertain middle, send that line to GPT (the expert).
     The report below simulates exactly that tradeoff on held-out data.

Data sources (all optional except synthetic.csv):
  data/synthetic.csv       generated by generate_dataset.py
  data/custom_labeled.csv  your hand-labeled real lines
  data/gpt_labeled.csv     lines GPT classified at runtime (feedback loop)

Usage:
  python train.py                 # train, report metrics, save model
"""

import csv
import json
from datetime import datetime, timezone
from pathlib import Path

import joblib
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

ML_DIR = Path(__file__).parent
DATA_DIR = ML_DIR / "data"
MODEL_DIR = ML_DIR / "model"

# Below this probability distance from 0.5, a prediction is "uncertain"
# and would be routed to GPT. 0.9 means: trust the model only when it says
# >= 90% subscription or <= 10% subscription.
CONFIDENCE_THRESHOLD = 0.90


def load_dataset():
    """Load every CSV we have, merge, and de-duplicate.

    De-duplication matters: the synthetic generator repeats merchants many
    times, and if identical lines land in both train and test splits the
    test accuracy becomes a lie (the model already saw the answer).
    """
    texts, labels, sources = [], [], []
    seen = set()
    files = ["synthetic.csv", "custom_labeled.csv", "gpt_labeled.csv"]
    for name in files:
        path = DATA_DIR / name
        if not path.exists():
            continue
        count = 0
        with open(path, newline="", encoding="utf-8") as f:
            for row in csv.DictReader(f):
                text = row["text"].strip()
                key = text.lower()
                if not text or key in seen:
                    continue
                seen.add(key)
                texts.append(text)
                labels.append(int(row["label"]))
                count += 1
        sources.append(f"  {name}: {count} unique lines")
    print("Loaded data:")
    print("\n".join(sources))
    return texts, np.array(labels)


def build_pipeline() -> Pipeline:
    """Vectorizer + classifier as one object, so the exact same text
    transformation is applied at training AND prediction time."""
    return Pipeline([
        ("tfidf", TfidfVectorizer(
            analyzer="char_wb",      # character n-grams within word boundaries
            ngram_range=(2, 5),      # fragments of 2 to 5 characters
            lowercase=True,
            min_df=2,                # ignore fragments seen only once (noise)
            sublinear_tf=True,       # dampen very frequent fragments
        )),
        ("clf", LogisticRegression(
            max_iter=1000,
            C=1.0,                   # regularization strength (lower = simpler model)
            class_weight="balanced", # don't let the bigger class dominate
        )),
    ])


def report_confidence_routing(pipe, X_test, y_test):
    """Simulate the runtime routing: how many test lines would the local
    model handle on its own, and how accurate is it on those?"""
    proba = pipe.predict_proba(X_test)[:, 1]  # P(subscription) per line
    confident = (proba >= CONFIDENCE_THRESHOLD) | (proba <= 1 - CONFIDENCE_THRESHOLD)

    n_local = int(confident.sum())
    n_gpt = len(X_test) - n_local
    print(f"\n--- Confidence routing simulation (threshold {CONFIDENCE_THRESHOLD}) ---")
    print(f"Handled locally : {n_local}/{len(X_test)} ({n_local / len(X_test):.1%})")
    print(f"Sent to GPT     : {n_gpt}/{len(X_test)} ({n_gpt / len(X_test):.1%})")

    if n_local:
        local_preds = (proba[confident] >= 0.5).astype(int)
        local_acc = accuracy_score(y_test[confident], local_preds)
        print(f"Accuracy on locally-handled lines: {local_acc:.4f}")
    return proba


def main():
    texts, labels = load_dataset()

    # Hold out 20% the model NEVER sees during training. Metrics on this
    # split estimate how the model behaves on future, unseen lines.
    # stratify keeps the sub/non-sub ratio identical in both splits.
    X_train, X_test, y_train, y_test = train_test_split(
        texts, labels, test_size=0.20, random_state=42, stratify=labels
    )
    print(f"\nTrain: {len(X_train)} lines | Test: {len(X_test)} lines")

    pipe = build_pipeline()
    pipe.fit(X_train, y_train)

    # --- Overall metrics on the held-out split ---
    preds = pipe.predict(X_test)
    acc = accuracy_score(y_test, preds)
    print(f"\n--- Held-out test metrics ---")
    print(f"Accuracy: {acc:.4f}")
    print(classification_report(y_test, preds,
                                target_names=["not-sub", "subscription"]))
    tn, fp, fn, tp = confusion_matrix(y_test, preds).ravel()
    print(f"Confusion: TP={tp} TN={tn} FP={fp} FN={fn}")
    print("  (FP = flagged as sub but isn't; FN = missed a real sub)")

    report_confidence_routing(pipe, X_test, y_test)

    # --- Retrain on ALL data before saving ---
    # The held-out split measured generalization; now that we have the
    # measurement, we let the final saved model learn from every line.
    pipe.fit(texts, labels)

    MODEL_DIR.mkdir(exist_ok=True)
    model_path = MODEL_DIR / "classifier.joblib"
    joblib.dump(pipe, model_path)

    meta = {
        "trained_at": datetime.now(timezone.utc).isoformat(),
        "n_samples": len(texts),
        "test_accuracy": round(float(acc), 4),
        "confidence_threshold": CONFIDENCE_THRESHOLD,
        "sklearn_pipeline": "TfidfVectorizer(char_wb 2-5) + LogisticRegression",
    }
    with open(MODEL_DIR / "metadata.json", "w") as f:
        json.dump(meta, f, indent=2)

    print(f"\nSaved model to {model_path}")
    print(f"Metadata: {json.dumps(meta, indent=2)}")


if __name__ == "__main__":
    main()
